parameters:
#    zenezorej_admin_pages.example.class: Zenezorej\AdminPagesBundle\Example

services:
#    zenezorej_admin_pages.example:
#        class: %zenezorej_admin_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
