parameters:
#    zenezorej_base.example.class: Zenezorej\BaseBundle\Example

services:
#    zenezorej_base.example:
#        class: %zenezorej_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
