parameters:
#    zenezorej_acknowledgements.example.class: Zenezorej\AcknowledgementsBundle\Example

services:
#    zenezorej_acknowledgements.example:
#        class: %zenezorej_acknowledgements.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
