parameters:
#    zenezorej_zorej_tv.example.class: Zenezorej\ZorejTvBundle\Example

services:
#    zenezorej_zorej_tv.example:
#        class: %zenezorej_zorej_tv.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
