parameters:
#    zenezorej_events.example.class: Zenezorej\EventsBundle\Example

services:
#    zenezorej_events.example:
#        class: %zenezorej_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
