parameters:
#    zenezorej_demo.example.class: Zenezorej\DemoBundle\Example

services:
#    zenezorej_demo.example:
#        class: %zenezorej_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
