zenezorej_user_pages:
    resource: "@ZenezorejUserPagesBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_base:
    resource: "@ZenezorejBaseBundle/Resources/config/routing.yml"
    prefix:   /

