zenezorej_zorej_tv:
    resource: "@ZenezorejZorejTvBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_demo:
    resource: "@ZenezorejDemoBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_philosophy:
    resource: "@ZenezorejPhilosophyBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_main:
    resource: "@ZenezorejMainBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_base:
    resource: "@ZenezorejBaseBundle/Resources/config/routing.yml"
    prefix:   /

