zenezorej_acknowledgements:
    resource: "@ZenezorejAcknowledgementsBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_publications:
    resource: "@ZenezorejPublicationsBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_events:
    resource: "@ZenezorejEventsBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_zorej_tv:
    resource: "@ZenezorejZorejTvBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_demo:
    resource: "@ZenezorejDemoBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_philosophy:
    resource: "@ZenezorejPhilosophyBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_main:
    resource: "@ZenezorejMainBundle/Resources/config/routing.yml"
    prefix:   /

zenezorej_base:
    resource: "@ZenezorejBaseBundle/Resources/config/routing.yml"
    prefix:   /

