security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    
    access_control:
    - { path: ^/kapcsolat/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
    - { path: ^/kapcsolat, roles: ROLE_USER }

    firewalls:
        secured_area:
            pattern:   ^/kapcsolat
            anonymous: ~
            form_login:
                login_path:  security_login
                check_path:  security_login_check

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
