parameters:
#    zenezorej_guest_room.example.class: Zenezorej\GuestRoomBundle\Example

services:
#    zenezorej_guest_room.example:
#        class: %zenezorej_guest_room.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
