parameters:
#    zenezorej_user_pages.example.class: Zenezorej\UserPagesBundle\Example

services:
#    zenezorej_user_pages.example:
#        class: %zenezorej_user_pages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
